alias: Turn Off Pool Heater at Sunset
description: ""
trigger:
  - platform: sun
    event: sunset
    offset: 0
condition:
  - condition: state
    state: "on"
    entity_id: binary_sensor.pool_heater
action:
  - data: {}
    target:
      entity_id: climate.aquatemp
    action: climate.turn_off
  - data:
      hvac_mode: "off"
    target:
      entity_id: climate.aquatemp
    action: climate.set_hvac_mode
mode: single
