alias: Turn Up Consumption of Pool
description: Based on an increase in Solar Availability, turn pool heater up
trigger:
  - platform: numeric_state
    entity_id: sensor.solarnet_combined_power_grid
    for:
      hours: 0
      minutes: 5
      seconds: 0
    below: -1500
condition:
  - condition: state
    state: "on"
    entity_id: binary_sensor.pool_heater
  - condition: not
    conditions:
      - condition: state
        entity_id: climate.aquatemp
        attribute: fan_mode
        state: auto
action:
  - data:
      fan_mode: auto
    target:
      entity_id: climate.aquatemp
    action: climate.set_fan_mode
  - metadata: {}
    data:
      temperature: 35
      hvac_mode: auto
    target:
      entity_id: climate.aquatemp
    action: climate.set_temperature
mode: single
