alias: Turn Down Consumption of Pool
description: >-
  Sets Fan Speed to Low in the case that the pool heater is on and solar
  consumption disappears
trigger:
  - platform: numeric_state
    entity_id: sensor.solarnet_combined_power_grid
    for:
      hours: 0
      minutes: 5
      seconds: 0
    above: -200
condition:
  - condition: state
    state: "on"
    entity_id: binary_sensor.pool_heater
  - condition: not
    conditions:
      - condition: state
        entity_id: climate.aquatemp
        attribute: fan_mode
        state: low
action:
  - data:
      fan_mode: low
    target:
      entity_id: climate.aquatemp
    action: climate.set_fan_mode
mode: single
