alias: Turn Down Temperature based on Inlet Temp
description: >-
  Sets target temp to 2deg less than inlet temp to stop the heatpump case that
  the pool heater is on and solar consumption disappears
trigger:
  - platform: numeric_state
    entity_id: sensor.solarnet_combined_power_grid
    for:
      hours: 0
      minutes: 5
      seconds: 0
    above: -200
condition:
  - condition: state
    state: "on"
    entity_id: binary_sensor.pool_heater
  - condition: not
    conditions:
      - condition: state
        entity_id: climate.aquatemp
        attribute: fan_mode
        state: auto
action:
  - target:
      entity_id: number.pool_inlet_temp_less_two
    data:
      value: "{{ state_attr('climate.aquatemp', 'inlet_temperature')|float - 2.0 }}"
    enabled: false
    action: number.set_value
  - metadata: {}
    data:
      temperature: "{{ state_attr('climate.aquatemp', 'inlet_temperature')|float - 2.0 }}"
      hvac_mode: auto
    target:
      entity_id: climate.aquatemp
    action: climate.set_temperature
mode: single
