alias: Turn On Pool Heater
description: Turn on pool heater when solar production is over 2.6kw for 10 minutes
trigger:
  - platform: numeric_state
    entity_id:
      - sensor.solarnet_combined_power_grid
    for:
      hours: 0
      minutes: 10
      seconds: 0
    below: -2600
condition:
  - condition: state
    entity_id: weather.forecast_home
    state:
      - sunny
      - partlycloudy
      - exceptional
      - windy
    enabled: false
  - condition: not
    conditions:
      - condition: state
        entity_id: climate.aquatemp
        attribute: is_fault
        state: "false"
  - condition: not
    conditions:
      - condition: state
        entity_id: binary_sensor.pool_heater
        state: "on"
action:
  - data: {}
    target:
      entity_id: climate.aquatemp
    action: climate.turn_on
  - data:
      fan_mode: auto
    target:
      entity_id: climate.aquatemp
    action: climate.set_fan_mode
  - metadata: {}
    data:
      temperature: 35
      hvac_mode: auto
    target:
      entity_id: climate.aquatemp
    action: climate.set_temperature
  - metadata: {}
    data:
      hvac_mode: auto
    target:
      entity_id: climate.aquatemp
    enabled: false
    action: climate.set_temperature
mode: single
